lexical_es = {'first_person_singular': ['yo', 'mio', 'mi'],
              'second_person_singular': ['tú', 'tu', 'tuyo', 'usted', 'vos'],
              'third_person_singular': ['él', 'el', 'ella', 'ese', 'esa', 'aquel'],
              'first_person_plurar': ['nosotros', 'nuestros'],
              'second_person_plurar': ['tuyos', 'tuyas', 'ustedes', 'vosotros', 'vosotras'],
              'third_person_plurar': ['ellos', 'ellas', 'ese', 'esos', 'aquellas', 'aquellos'],
              'adverb_time': ['ya', 'aún', 'hoy', 'tarde', 'pronto', 'todavía', 'ayer', 'recién', 'nunca', 'siempre',
                              'jamás', 'ahora'],
              'adverb_neg': ['tampoco', 'no', 'en absoluto', 'nunca'],
              'adverb_place': ['ahí', 'allí', 'aquí', 'acá', 'delante', 'detrás', 'arriba', 'abajo', 'cerca', 'lejos',
                               'encima', 'fuera', 'dentro'],
              'adverb_mode': ['mal', 'bien', 'regular', 'despacio', 'así', 'mejor', 'peor', 'claro', 'similar',
                              'fácilmente'],
              'adverb_cant': ['muy', 'más', 'poco', 'bastante', 'bastante', 'menos', 'mucho', 'algo', 'casi'],
              'adjetives_neg': ['aburrido', 'ácido', 'amargo', 'ancho', 'atrevido', 'bajo', 'blando', 'caliente',
                                'común', 'conocido', 'corto', 'débil', 'delgado', 'diferente', 'difícil', 'duro',
                                'enfermo', 'estrecho', 'falso', 'feo', 'frío', 'húmedo', 'imposible', 'izquierdo',
                                'lento', 'malo', 'menor', 'muerto', 'negro', 'peor', 'pequeño', 'pobre', 'poco',
                                'popular', 'raro', 'rojo', 'salado', 'simple', 'sinvergüenza', 'solo', 'soso',
                                'tímido', 'tonto', 'triste', 'viejo'],
              'adjetives_pos': ['alegre', 'alto', 'azul', 'blanco', 'bonito', 'buen', 'bueno', 'caliente', 'capaz',
                                'central', 'contento', 'derecho', 'diferente', 'divertido', 'dulce', 'duro', 'exterior',
                                'famoso', 'final', 'fresco', 'fuerte', 'gran', 'grande', 'guapo', 'guay', 'igual',
                                'imposible', 'interesante', 'joven', 'largo', 'listo', 'mayor', 'mejor', 'mucho',
                                'musical', 'nacional', 'natural', 'nuevo', 'perfecto', 'popular', 'posible',
                                'primer', 'primero', 'principal', 'próximo', 'rápido', 'real', 'recto', 'rico',
                                'salado', 'sano', 'seco', 'útil', 'verdadero', 'verde', 'vivo'],
              'who_general': ['familia', 'familiar', 'familiares', 'acompañante', 'aprendices', 'aprendiz', 'artista',
                              'asistente', 'compinche', 'directiva', 'directivo', 'especialista', 'estudiante',
                              'estudiantes', 'joven', 'jovenes', 'lider', 'pareja', 'projimo'],
              'who_male': ['abuelo', 'alcalde', 'medico', 'alumno', 'alumnos', 'amigo', 'amigos', 'asesor', 'chiquillo',
                           'compa', 'compadre', 'compañero', 'compañeros', 'decano', 'director', 'doctor', 'empleado',
                           'empresario', 'entrenador', 'esposo', 'esposito', 'experto', 'expertos', 'funcionario',
                           'hermano', 'ingeniero', 'investigador', 'jefe', 'jugador', 'padre', 'marido', 'medico',
                           'muchacho', 'muchachos', 'niño', 'niños', 'novio', 'hijo', 'primo', 'papa', 'pequeños',
                           'profesor', 'pequeño', 'secretario', 'socio', 'tutor', 'papi', 'tio', 'nieto'],
              'who_female': ['alumna', 'alumnas', 'amiga', 'amigas', 'asesora', 'chiquilla', 'comadre', 'compañera',
                             'compañeras', 'dama', 'decana', 'directora', 'doctora', 'empleada', 'empresaria', 'esposa',
                             'esposita', 'experta', 'expertas', 'funcionaria', 'hermana', 'ingeniera', 'investigadora',
                             'jefa', 'jugadora', 'madre', 'mama', 'medica', 'muchacha', 'muchachas', 'mujer', 'niñas',
                             'novia', 'novicia', 'hija', 'prima', 'pequeña', 'pequeñas', 'profesora', 'secretaria',
                             'señora', 'socia', 'tutora', 'mami', 'tia', 'nieta'],
              'hate': ['animosidad', 'antagonismo', 'enemistad', 'odio', 'horror', 'hostilidad', 'aborrecimiento',
                       'dolor', 'rencor', 'resentimiento', 'venganza', 'veneno', 'aborrecimiento', 'abominación ',
                       'anatema', 'animus', 'antipatía', 'aversión', 'molestar', 'bugbear', 'detestación ', 'disgusto',
                       'execración', 'escarcha', 'agravio', 'queja', 'irritante', 'malevolencia', 'malignidad',
                       'molestia', 'objeción', 'odio', 'irritación', 'repugnancia', 'repulsión', 'repulsión',
                       'desprecio', 'despecho', 'problemas', 'bestia negra', 'mala voluntad', 'desagradable',
                       'mirada desagradable', 'ningún amor perdido'],


              'emoji_pos': ['😂', '🤣', '😀', '😃', '😄', '😁', '😊', '😍', '😘', '😙', '😜', '😉', '😎', '🥰',
                            '❤', '♥', '💚', '💙', '💜', '❣', '💞', '💕', '👍', '👌', '👏', '🙌', '🎉', '✨',
                            '🌟', '💪', '🙏', '💃'],
              'emoji_neg': ['😢', '😭', '😞', '😔', '😒', '😩', '😫', '😠', '😡', '🤬', '💔', '👎', '😱', '😤',
                            '😣', '😖', '🙄'],
              'laugh': ['xd', 'lol', 'lmao', 'jsjs', 'jsjsjs', '🤣'],
              'negation': ['no', 'nunca', 'jamás', 'jamas', 'tampoco', 'ni', 'nada', 'nadie', 'sin'],
              'adversative': ['pero', 'aunque', 'sino'],

              
              'doubt_phrases': ['no se', 'no sé', 'puede que', 'creo que', 'tal vez', 'quizas', 'quizás',
                                'a lo mejor', 'no estoy seguro', 'no estroy seguro', 'no estoy segura',
                                'me parece que', 'me da la impresion', 'me da la impresión', 'quizá',
                                'no tengo claro', 'no lo tengo claro', 'no estoy convencido', 'no estoy convencida',
                                'podria ser', 'podría ser', 'tengo dudas', 'no lo se', 'no lo sé',
                                'si no me equivoco', 'igual', 'de pronto', 'en una de esas',
                                'es posible que', 'puede ser que', 'probablemente', 'seguramente no'],
              'regionalisms': ['sumercé', 'sumerce', 'parce', 'parcero', 'parcera', 'bacano', 'berraco', 'chévere',
                               'chevere', 'vale', 'tio', 'tía', 'tia', 'guay', 'chido', 'pana', 'manito',
                               'wey', 'güey', 'guey', 'órale', 'orale', 'vaina', 'chamba', 'bacán', 'bacan',
                               'mae', 'pibe', 'piba', 'boludo', 'boluda', 'che', 'copado', 'copada',
                               'currar', 'curro', 'anda ya', 'mola', 'chaval', 'chavala', 'de una', 'de una vez'],
              'intensifiers': ['super', 'súper', 'muy', 're', 'mega', 'hiper', 'demasiado', 'bien',
                               'bastante', 'sumamente', 'altamente', 'tan', 'muchisimo', 'muchísimo',
                               'full', 'ultra', 'extra', 'remuy', 'requete', 'harto', 'bien bien',
                               'super super', 'muy muy']}

